### ISSUE TITLE
mT23ClearIntFlag and other instructions not recognize for UNO32

### ISSUE THREAD

**Issue by michastro** [UECIDE/UECIDE#101]
Hello,
I have reinstalled completely my laptop and when I try to compile my program for UNO32, the instructions like:
mT23ClearIntFlag
mT45ClearIntFlag
...
are not recognized. I have selected UNO32 for the board.
thanks
Michel

**Comment by majenkotech** [comment]
These are PLIB macros and the compiler no longer includes them. There is a plugin for the older compiler but there are no guarantees that it will work with the current core. You should switch to using the proper chipKIT functions.
