### ISSUE TITLE
Standard window functionality support

### ISSUE THREAD

**Issue by sensboston** [UECIDE/UECIDE#110]
Could you please add standard Windows functionality to the UECIDE main window? Now program for some strange reasons modified standard window menu, and only "Close window" choice is available (no "Pin to taskbar", no grouping etc.)

I don't know why this strange functionality was implemented, but it's kinda unuseful and annoying.

**Comment by majenkotech** [comment]
I don't know what "functionality" you are referring to. I have not "implemented" anything. The window is just a standard JFrame with whatever that provides. There are various themes you can install and select, so maybe one of those is installed and changing it? Not using Windows I have no clue what you're on about.

**Comment by majenkotech** [comment]
I think I have (now my Windows PC has finally been booted long enough for the mouse buttons to actually do anything when pressed ... jeez... how do you guys use this pile of crap?) found the menu to which you are referring - you mean a right click on the window icon in the task bar, yes?

UECIDE is a Java application. That one entry is all you get for a Java application. There's nothing you can do about it. It's Java.

You want it pinned to the taskbar then right-click the shortcut and pin it to the taskbar. There's absolutely nothing at all you can do from within a Java program to change a menu that only exists at the whim of the operating system it's running in.

Java is cross-platform. Platform- (and especially version-specific platform-) specific things like a context menu on a taskbar entry are nothing that Java ever even wants to consider touching.

**Comment by sensboston** [comment]
OK, thanks for explanation.

**Comment by sensboston** [comment]
I found a simple workaround. If you not a principal Windows hater (BTW, for the real professional, OS shouldn't matter much), you may add it in FAQ section.

![2018-10-06](https://user-images.githubusercontent.com/1036158/46576004-4da50700-c98e-11e8-9138-c2141992ffe5.png)

- create shortcut to javaw.exe on your desktop.
- add to the shortcut executable path ``-jar "C:\Program Files (x86)\Majenko Technologies\UECIDE\lib\uecide.jar``, so whole patch should look like ``-jar "C:\Program Files (x86)\Majenko Technologies\UECIDE\lib\uecide.jar"``
- change "Start in" to ``C:\Program Files (x86)\Majenko Technologies\UECIDE``
- change icon to ``C:\Program Files (x86)\Majenko Technologies\UECIDE\UECIDE.ico``
- pin shortcut to the taskbar
- delete shortcut

**Comment by majenkotech** [comment]
Can't you just right-click on the icon in the start menu and pin to taskbar?

**Comment by sensboston** [comment]
Yes I can, but in this case, if I run this shortcut, running java app will appear as an additional, separate icon on the taskbar, and Windows will not group these icons. Of course, it's not a big issue but if you're working on Windows, this is standard common programm behavior. 

P.S. @majenkotech, may I ask you to add ability to load last opened project to the IDE settings? It will be really good feature.

**Comment by majenkotech** [comment]
It's already there. Check preferences (Editor -> Load/Save -> [X] Open last sketch automatically)

**Comment by sensboston** [comment]
Thanks!

**Comment by sensboston** [comment]
BTW, my solution doesn't work properly - UECIDE opened by this way, crashes immediately on chip programming step (don't know why, no error messages was received - just a simple crash).
