### ISSUE TITLE
Improve functionality by using selected text as argument for Search/Replace

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#122]
When the user press CTRL-F while editing, the selected text (or clipboard) must be used as Search/Replace argument.

**Comment by majenkotech** [comment]
That's a great idea. And easy enough to implement too.

**Comment by majenkotech** [comment]
I think the answer is yes. With it like that you can just highlight a word and keep pressing CTRL-F and it cycles through all the instances of it.  That's nice.

Added in 7d2994d
