### ISSUE TITLE
Clear button for Serial Terminal

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#127]
**Is your feature request related to a problem? Please describe.**
I want to clear the `Serial Terminal `window before starting a new run or after some event in the program, to avoid confusion between old and new data displayed.

**Describe the solution you'd like**
A `Clear` button in the `Serial Terminal` window that erase all content.

**Describe alternatives you've considered**
Closing and reopening the `Serial Terminal`, but that means a program reset. Not good when in the middle of something.

**Comment by majenkotech** [comment]
Also an option in Preferences to auto-clear when you open the window, or when the port is opened could be good.

**Comment by majenkotech** [comment]
Added in 9359928
