### ISSUE TITLE
Explicit save button for Serial Terminal

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#128]
**Is your feature request related to a problem? Please describe.**
While `Serial Terminal` can save its window content to a file, that option is invisible and can only be discovered by trial-and-error.

**Describe the solution you'd like**
A `Save` button in the `Serial Terminal` window.

**Comment by majenkotech** [comment]
Maybe also live capture to file would be useful.

**Comment by SantoRemedio** [comment]
Maybe you can use that so PC programs can get real time data from Arduino thru a file/pipe.

**Comment by majenkotech** [comment]
Added in 9359928
