### ISSUE TITLE
UnInstall on Linux mint leaves modified icon and UECIDE as default application

### ISSUE THREAD

**Issue by bperrybap** [UECIDE/UECIDE#13]
When UECIDE is installed, it makes itself the default application for .pde files
and changes the icon.
However, when un-installed through the linux mint synaptic package manager,
it leaves the default application as uecide along with the changed icon.

I was using linux mint13 32bit mate.
I noticed this on both Nautilus and Caja.

Seems like it should remove itself completely and not leave any
remnants behind.

**Comment by majenkotech** [comment]
Closed: not relevant for current packaging
