### ISSUE TITLE
Multiple tabs alternative navigation

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#137]
**Is your feature request related to a problem? Please describe.**
When dealing with multiple files opened (in multiple tabs), selecting a particular open one is difficult because you need to navigate across tabs using only "prev" and "next" buttons, multiple times, without a hint of where is that particular tab located (to the right or to the left), because tabs doesn't fit in the panel space. This is cumbersome and slow.

![Actual](https://user-images.githubusercontent.com/46725121/54113197-8d04d300-43c6-11e9-8178-5a09f9f8b9ca.png)

**Describe the solution you'd like**
Replace the "prev" and "next" buttons with a drop box scrollable list showing all open tabs.

![Proposed](https://user-images.githubusercontent.com/46725121/54113271-ac036500-43c6-11e9-8aad-3b67ef698cc2.png)

**Describe alternatives you've considered**
Using the Project pane for selecting file/tab. This is not optimal, because you need to double click on the file name, which expand/collapse the tree at that point, which is an unwanted side effect.

**Comment by majenkotech** [comment]
Unfortunately I don't get that sort of control over a jtabbedpane. It's not possible to add a menu like that as far as I know. However I could add a mouse listener and create a right click popup menu on the tabs themselves which lists all the tabs. Would that be a suitable work around?

**Comment by SantoRemedio** [comment]
That's a nice and convenient solution.

**Comment by majenkotech** [comment]
Some themes already provide that extra menu button. Not all, but some. It's down to the theme to provide it, not the software. 

However I have added a right-click menu anyway as an alternative way of doing the same thing - so whatever theme you have selected it should make navigating tabs easier.
