### ISSUE TITLE
File changed indicator/action

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#139]
**Is your feature request related to a problem? Please describe.**
It's convenient a visual indication when source files has been modified since last compilation, mainly to avoid changing the code and then forgetting to recompile/upload the upgraded sketch.

The question is: Did I recompile and upload this code? Not sure? Recompile and upload again can be slow.

**Describe the solution you'd like**
A icon on the file tab (editor pane) to indicate changes from last compilation. It can be a single "*" in from of the file name.

**Describe alternatives you've considered**
This is a standard approach for others IDE.

**Comment by majenkotech** [comment]
I used to have indication of changes since last save. Not sure how possible an indication like that per file for changes since last compile or upload.

I could always have the compilation routine modify your source code for you.  Have it look for a comment starting

    // $Compiled: 

and add the compilation time and date to the end of it:

    // $Compiled: Sat, 16 Mar 2019 20:08:32 +0000

**Comment by SantoRemedio** [comment]
"Changed since last save" is OK. My setup saves the source files before compiling, anyway.

I don't think "$Compiled" is a practical idea. It require for me to visually inspect each open tab to check if the file has changed.  And it's not clear the semantic when you mix .ino, .cpp and .h. What happens when a globally used .h changes?

**Comment by majenkotech** [comment]
Changed since last save is on my list of things to reinstate. 

At the moment the system's not clever enough to know to recompile source files if an included header has changed. It would be nice if it was, but that would be a mammoth task to implement and mess up the whole of the existing compilation structure.

**Comment by majenkotech** [comment]
As part of my revamp of the UI, and the adding of a new LAF (Material look) I have some interesting chages.  For instance, the tab now has a modified warning icon. Things have been tidied up a little, and I've just tried to make it more "refined"...

![NewLook](https://user-images.githubusercontent.com/3812892/55264192-76d29000-526b-11e9-82af-b9896f64ef25.png)

Thoughts?

**Comment by SantoRemedio** [comment]
Very nice look!

Personal preferences:

1) "Cancel" instead of "Don't close". One word vs. two (or three).
2) "Save" and "Discard". One word, both meaning positive actions (save, discard) rather than absence of action (negative action).
3) Button order: "Discard", "Cancel", "Save". Because "Cancel, Save" at the right is the most generic and consistent way to arrange any kind of dialog, with extra options to the left. 

There is no standard in Linux about the button order or action semantic. Standards are different between Windows and Mac. That's a problem for a multi platform product like UECIDE. Must be dialogs adaptative to platform guidelines?

I like the MacOS user interface guidelines: 

> A button that initiates an action is furthest to the right. The Cancel button is to the left of this button.

![Screenshot at 2019-03-30 06-54-50](https://user-images.githubusercontent.com/46725121/55274630-cab79600-52b8-11e9-8989-62a3c6ba17aa.png)

Which is consistent with Android guideline:

> The dismissive action of a dialog is always on the left. Dismissive actions return to the user to the previous state.
> 
> The affirmative actions are on the right. Affirmative actions continue progress toward the user goal that triggered the dialog.
> 

For more details, look at this: [OK/Cancel on left/right?](https://ux.stackexchange.com/questions/1072/ok-cancel-on-left-right)

In Linux, no standard or convention whatsoever, but pure and simple chaos. Here is a sample of some apps I use:

### Arduino IDE
![Screenshot at 2019-03-30 06-31-31](https://user-images.githubusercontent.com/46725121/55274288-85de3000-52b5-11e9-9541-4b84004db630.png)
Button "Yes" means "save".

### PulseView
![Screenshot at 2019-03-30 06-35-44](https://user-images.githubusercontent.com/46725121/55274340-1b79bf80-52b6-11e9-8e5c-2334fbfda1f0.png)
Button "Yes" means "discard".

### Netbeans
![Screenshot at 2019-03-30 06-39-12](https://user-images.githubusercontent.com/46725121/55274397-92af5380-52b6-11e9-83d5-632810a01225.png)

### Libre Office
![Screenshot at 2019-03-30 06-46-14](https://user-images.githubusercontent.com/46725121/55274467-8ed00100-52b7-11e9-9895-143eb7adbe9d.png)

### Shotcut
![Screenshot at 2019-03-30 07-25-09](https://user-images.githubusercontent.com/46725121/55274926-07858c00-52bd-11e9-96e3-7adf65b9b74c.png)

**Comment by majenkotech** [comment]
Here it is reworded and reorderd - also with the new Arduino theme I am working on (ghastly, but people seem to like the way the Arduino IDE looks... weirdos...)

![CloseDialog](https://user-images.githubusercontent.com/3812892/55295553-44a96580-5406-11e9-9362-d1d2e22b7c25.png)

**Comment by SantoRemedio** [comment]
For me is good enough, but one more suggestion:

You can add file/sketch to the title bar ("unsaved file - . So, after a time, a UECIDE daily user just look at the title bar, which contains all the needed information. 

(I just photoshopped your dialog. It may not be evident at first sight)
![title](https://user-images.githubusercontent.com/46725121/55295794-bb833600-53e7-11e9-87a9-589e68045aca.png)

If file/sketch name is too long, it can be truncated, because it's in full in the message body.

**Comment by majenkotech** [comment]
Sure, that's simple enough.
![Unsaved3](https://user-images.githubusercontent.com/3812892/55296300-3c095d00-540f-11e9-8aa7-3288fa2312e5.png)
