### ISSUE TITLE
Add file name/project name to Unsaved File dialog

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#140]
**Is your feature request related to a problem? Please describe.**
When quitting UECIDE, a dialog is shown if there are unsaved files.
![Screenshot at 2019-03-17 06-35-33](https://user-images.githubusercontent.com/46725121/54488356-a05ce600-487f-11e9-98ec-4de12a6bd7fa.png)
The dialog doesn't name the file, nor its project. That information is needed to decide what to do next.

**Describe the solution you'd like**
1. Modify the dialog to show the file and project name.
2. Bring the project window and file tab to the the front, underneath the dialog.
![Screenshot at 2019-03-17 06-35-323](https://user-images.githubusercontent.com/46725121/54488530-76a4be80-4881-11e9-8293-c9ff34bdc2aa.png)

**Describe alternatives you've considered**
None.

**Comment by majenkotech** [comment]
I can't get the tab or window to focus, because it all happens in the event handling thread and that thread needs to finish the current iteration before the swing thread can process any requests to modify the window. It's a problem of blocking dialog boxes. Not a lot I can do about that. However I have got it to show the program and file name in the dialog.

**Comment by SantoRemedio** [comment]
I can suggest two variants:
- a single dialog listing all unsaved files, with buttons "Cancel" and "Save All".
- a dialog for each file, with buttons "Cancel", "Save" and "Save All". It this case, the IDE stop asking any more question.

**Comment by majenkotech** [comment]
I already changed the wording of the buttons. This is how the close dialog looks at the moment:

![close](https://user-images.githubusercontent.com/3812892/54918533-7007ee00-4ef6-11e9-8be2-86f6d33b51bd.png)

**Comment by majenkotech** [comment]
I'm also considering a dialog box a bit like the Gimp one.

**Comment by SantoRemedio** [comment]
I like the Gimp dialog better. It works with multiple unsaved files, because it's only one dialog and it shows all unsaved files at once.
![Screenshot at 2019-03-25 12-46-10](https://user-images.githubusercontent.com/46725121/54933756-fffc6680-4efb-11e9-8c23-917fa8dc4f5c.png)
 
For the one-file-save dialog, I will propose a change in name font/style/size/color, to make it stand out.

**Comment by majenkotech** [comment]
The problem I have with the Gimp-style box is I'd like one box that covers all sketches if you do a quit. However that's not possible with UECIDE - it just sends a "quit" signal to each window in turn, and it's up to that window to ask if it should close or not.  So you could still potentially get multiple dialogs. However it would only be one per UECIDE window, so not *too* bad...

**Comment by majenkotech** [comment]
I'm going to keep it as it is for now. It's improved, with the new wording, but
