### ISSUE TITLE
Serial Terminal Pause Status Indicator

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#143]
**Is your feature request related to a problem? Please describe.**
The button Pause for the Serial Terminal shows minimal differences between paused/normal state, and no hint about what status it is.

Normal status:
![Screenshot at 2019-03-24 10-48-56](https://user-images.githubusercontent.com/46725121/54880341-762c9a80-4e22-11e9-865f-13322b64dc8b.png)

Paused status:
![Screenshot at 2019-03-24 10-46-48](https://user-images.githubusercontent.com/46725121/54880343-79278b00-4e22-11e9-9dd0-0c40aae3788f.png)

**Describe the solution you'd like**
Change the _Pause_ button to a _Play_ button when paused.

**Comment by majenkotech** [comment]
Yes, that thought did cross my mind while creating that functionality. It is on the cards, but at a lower priority than just creating the functionality.

**Comment by majenkotech** [comment]
Added in ae7242d
