### ISSUE TITLE
Add Comment/Uncomment option to Edit menu

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#144]
**Is your feature request related to a problem? Please describe.**
While debugging code it is useful to comment out whole code sections, which latter must be restored (or vice-versa).

Presently this must be do manually, which is tedious and slow.

**Describe the solution you'd like**
It will be nice to have a Comment/Uncomment option in the Edit menu and maybe in the toolbar to comment/uncomment a block of selected lines (much as indent/unindent code works).

**Describe alternatives you've considered**
No alternative possible.

**Comment by majenkotech** [comment]
Or... just press `CTRL+SHIFT+C`...
