### ISSUE TITLE
Identify ports

### ISSUE THREAD

**Issue by SantoRemedio** [UECIDE/UECIDE#145]
**Is your feature request related to a problem? Please describe.**
The menu _Hardware->Device_ shows a list of available USB ports without any hint of what device (Uno, Mini, Nano, Wemos, ...) are connected to them. It neither shows whether the USB port is already taken by a UECIDE instance. Finally, while UECIDE can automatically pick the correct USB port when starting, it doesn't automatically change USB port when changing device (_Hardware->Device_).

![Untitled](https://user-images.githubusercontent.com/46725121/55323200-c9bb6b80-5454-11e9-80fa-dac3b76ff16e.png)

**Describe the solution you'd like**
1) Put the name of the board in the _Hardware->Device_ list. Also, if the board is already associated with an UECIDE instance, name the sketch in that instance:
![Untitled](https://user-images.githubusercontent.com/46725121/55323576-d096ae00-5455-11e9-992f-d64dd24535cb.png)
In this case, there are two devices (Arduino Nano and Wemos D1). There is only one instance the UECIDE, loaded with a sketch named _Watchdog2_, running on Nano. 
2) Assignments must also be exclusive: only one UECIDE instance associated to a giving port.
3) When changing boards, the USB port must be reassigned or disassociated.

**Describe alternatives you've considered**
Disconnect the other device, reconnect it, reassign the port.

**Comment by majenkotech** [comment]
That's not really possible. There's no way to know what is on the end of a serial connection. For CDC/ACM ports, as long as the VID/PID are unique to the board (which they seldom are) it's possible to associate it with a specific board type, but for FT232 / CP2012 / CH340 all I know is that it's a USB serial port. 

The only way to know what's there is if the bootloader can provide that information and there's some way of probing that information - and then of course UECIDE would have to have some way of querying that information, which would be different for every board type, and not practical to hard code - not to mention all the boards attached to the system would have to be reset and probed every time the serial port list wants to be updated, which would just be ghastly...

You do get the Manufacturer and Product strings if possible (OS permissions permitting) and it displays those. It's also supposed to store the last used serial port with a board in the preferences and select that port (if it exists) when you select that board. For CDC/ACM boards that's whatever the sketch (or bootloader if it's in the bootloader mode) provides. For others that's whatever's hardwired into the USB interface chip (or the driver if the chip doesn't provide them).

But it's not perfect. The port changes on some operating systems, depending on what order boards are connected in or when it's reset for bootloader mode.  Some boards don't have a serial port all the time.  The whole concept of the serial port being connected to the board on many boards is irrelevant. Having a serial port "associated" with a sketch is silly. If you want to force a sketch to always use the same port that's simple enough:

    #pragma port /dev/ttyUSB1

Then when you load the sketch, compile, or whatever, it will automatically switch to that serial port.  Of course, on Linux, plug your boards in in a different order and that becomes meaningless.

On Linux you are best off creating symbolic links for your USB ports based on VID/PID and serial number and adding those as extra ports in UECIDE - then you can know what the board is by the device name.  You use `udev` to do that for you.  I have the likes of:

    ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", ATTRS{serial}=="ADXRXUZE", 
        KERNEL=="ttyUSB*", MODE="0660", GROUP="plugdev", SYMLINK+="board/chipkit/max32"

in a udev rules file, then add `/dev/board/chipkit/max32` as an extra port in UECIDE's preferences - which you see in the ports menu as well as /dev/ttyUSB0 or whatever.
