### ISSUE TITLE
Total crash of the Plugin manager with 0.8.8alpha1 (OSX)

### ISSUE THREAD

**Issue by madias123** [UECIDE/UECIDE#62]
As posted into the uecide forum:
sadly on OSX 10.9 the plugin manager crashes (just clicking on any entry in the tree) without the possibility to repair. To fix it, the only possibility is to delete all files in the User/xxx/Libraries and go back to an old version and reinstall everything again. So I would recommend not to update to this version yet.

Java log file:
OS: macosx_i386
Version: 0.8.8alpha1
Build: 565
Exception: 
java.lang.NoClassDefFoundError: org/markdown4j/Markdown4jProcessor
    at org.uecide.plugin.PluginManager$11.valueChanged(PluginManager.java:383)

**Comment by deladriere** [comment]
I reverted to Version 0.8.7z36 but have still the same problem

**Comment by madias123** [comment]
If you can't wait for a fix, to this, but you'll ve to reinstall everything:
delete uecide from the program folder
delete the whole order: User/<your name>/Libraries/UECIDE
reinstall the older version
update all plugins.

**Comment by majenkotech** [comment]
Just booting my OS X VM to experiment to see what's happening.

**Comment by majenkotech** [comment]
From other comments it looks like it may be the markdown processor that is not being found.

**Comment by majenkotech** [comment]
Ok, so it was just a packaging problem.  I forgot to add the markdown jar file to github so it never got packaged with the distribution build.  New build running now.

**Comment by majenkotech** [comment]
New version is now up. Works on my OSX VM.

**Comment by madias123** [comment]
Thank, you rebuilding should work now.
But there are some boards missing?
For example:
Whole TI stuff
Arduino Due
maple (please don't up it anymore, it's broken :) )
See Pic at:
http://666kb.com/i/cw6imszmyz7ogr7e3.gif

**Comment by majenkotech** [comment]
Have you read the message at the top of the beta page?  It explains that it's using a new repo system and not all the packages are converted yet.

**Comment by madias123** [comment]
Do humans ever mind big/fat/bold signs? ;)

Seriously: Please do not add the leaflabs/maple stuff again. It's too old, and it won't work on a modern system (didn't got it to work on any OS) . We are developing the new STM32-Arduino API (running on Arduino 1.6), so this should be the better candidate for the whole STM32Fxxx systems.

**Comment by majenkotech** [comment]
That sounds great.  The maple port was low priority anyway, so I'll look to use the newer 1.6 core instead.  Would it be this repo? https://github.com/madias123/Arduino_STM32

**Comment by madias123** [comment]
Better bookmark this (my fork isn't up to date and more experimental)
https://github.com/rogerclarkmelbourne/Arduino_STM32
I will drop you a line, when we'll be ready!
Other thing:
On chipkit the whole low level stuff isn't found/linked: Some errors:
error: 'PPS_OUT_REFCLKO' was not declared in this scope
error: 'mapPps' was not declared in this scope
error: 'PPS_OUT_SDO1' was not declared in this scope

**Comment by majenkotech** [comment]
Forked.

Which board is that error for?

**Comment by madias123** [comment]
DP32 or chipkit UNO, but maybe I shoot my whole UECIDE installation. (But I think not)

**Comment by majenkotech** [comment]
Shouldn't give messages like that for UNO - that has no PPS in it.  I'll check the DP32 defs.

**Comment by madias123** [comment]
These were only examples, like error: 'REFOCONbits' was not declared in this scope, so the whole stuff not working. more examples:
variable or field '__ISR' declared void
error: 'INT_ENABLED' was not declared
'INTSetVectorPriority' was not declared

**Comment by majenkotech** [comment]
Sounds like you have some crossover incompatibility there.  You should really start from a clean system with this new repo.

**Comment by deladriere** [comment]
But they are also gone from Version 0.8.7z36 ?
Can't see the Calunium anymore for example
Maybe because I installed the Alpha before reinstalling Version 0.8.7z36 
?

**Comment by majenkotech** [comment]
The plugin manager is what defines what repo you look at.  You have the newer "alpha" plugin manager installed, so the old version of the IDE uses that.  If you want to run the two side by side you will need to implement two separate data directories.

**Comment by deladriere** [comment]
Thx !
Back on track by deleting the plugin manager

**Comment by madias123** [comment]
nop. no luck at all with wiping all: These are all the errors:
Compiling...
• Compiling sketch...
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino: In function 'void setup()':
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:92:22: error: 'INT_SPI_1_VECTOR' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:92:40: error: 'INT_PRIORITY_LEVEL_4' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:92:60: error: 'INTSetVectorPriority' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:93:43: error: 'INT_SUB_PRIORITY_LEVEL_0' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:93:67: error: 'INTSetVectorSubPriority' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:94:11: error: 'INT_SPI1TX' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:94:23: error: 'INT_ENABLED' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:94:34: error: 'INTEnable' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino: At global scope:
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:103:11: error: variable or field '__ISR' declared void
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:103:27: error: 'ipl4' was not declared in this scope
/Users/madias/Documents/uecide/PIC32/I2s/CS4334/CS4334-begin3/CS4334-begin3.ino:147:1: error: expected '}' at end of input
Failed compiling sketch

**Comment by majenkotech** [comment]
Good-o.  When this new plugin manager / repo system is properly off the ground it's going to revolutionize things somewhat.

Right, your code is using code for the old compiler. We're now running by default on the newer compiler.  There are some differences and some symbols not defined.

You don't use __ISR any more - you use just:

    void __attribute__((interrupt)) myIsr() {...}

And just use numbers for the priorities.

**Comment by deladriere** [comment]
can't wait to use your library repo
will it organize itself for the appropriate boards ?

**Comment by majenkotech** [comment]
Kind of, yes.  If you change the drop-down at the top it filters the libraries to just show the ones for that family.

**Comment by madias123** [comment]
hm, I must rethink all my IRQ's....
I2C looks also broken: (tested on uno/DP32)
/Users/madias/Library/uecide/libraries/Communications/chipkit/Wire/DTWI.cpp: In constructor 'DTWI0::DTWI0()':
/Users/madias/Library/uecide/libraries/Communications/chipkit/Wire/DTWI.cpp:1429:105: error: '_DTWI0_SCL_PIN' was not declared in this scope
/Users/madias/Library/uecide/libraries/Communications/chipkit/Wire/DTWI.cpp:1429:121: error: '_DTWI0_SDA_PIN' was not declared in this scope
/Users/madias/Library/uecide/libraries/Communications/chipkit/Wire/DTWI.cpp: In constructor 'DTWI1::DTWI1()':
/Users/madias/Library/uecide/libraries/Communications/chipkit/Wire/DTWI.cpp:1454:105: error: '_DTWI1_SCL_PIN' was not declared in this scope
/Users/madias/Library/uecide/libraries/Communications/chipkit/Wire/DTWI.cpp:1454:121: error: '_DTWI1_SDA_PIN' was not declared in this scope
Failed compiling libraries

**Comment by madias123** [comment]
and why is there a "plugin manager" under plugins?

**Comment by majenkotech** [comment]
Because the plugin manager itself is a plugin - though I am going to be moving it back into the core instead so I can do more magical things.

It looks like some of the board definitions in Ricklon's 1.6 core may be out of date - just updating.

**Comment by madias123** [comment]
Is there a documentation for setting up interrupts with the new compiler? Some things are clear to me, but not all....
so my old:
INTSetVectorPriority(INT_SPI_1_VECTOR, INT_PRIORITY_LEVEL_4);
	INTSetVectorSubPriority(INT_SPI_1_VECTOR, INT_SUB_PRIORITY_LEVEL_0);
	INTEnable(INT_SPI1TX, INT_ENABLED);
...
void __ISR(_SPI_1_VECTOR, ipl4) SPI1InterruptHandler(void)

will get to:
   setIntVector(_SPI_1_VECTOR, (isrFunc)SPI1InterruptHandler);
   setIntPriority(_SPI_1_VECTOR, 4, 0);
setIntEnable(INT_SPI1TX);
....
void __attribute__((interrupt(),????)) SPI1InterruptHandler(void) {

**Comment by majenkotech** [comment]
Pretty much.  The function though is just:

    void __attribute__((interrupt)) SPI1InterruptHandler() {
        //code in here
    }

No need to specify the priority or anything in the interrupt, just in the setIntPriority call. 

There is a document being drafted at the moment - it's going through the proof reading stage at the moment I believe.

**Comment by majenkotech** [comment]
Oh, and the symbols you want are:

    _SPI_1_VECTOR

and

    _SPI1_TX_IRQ

**Comment by madias123** [comment]
ok, thank you, I think, I've got it:
setIntVector(_SPI_1_VECTOR, (isrFunc)SPI1InterruptHandler);
setIntPriority(_SPI_1_VECTOR, 4, 0);
setIntEnable(_SPI1_TX_IRQ);
}
....
void __attribute__((interrupt)) SPI1InterruptHandler() { // I2s Data out
               SPI1BUF =bit24; // something to write
 clearIntFlag(_SPI1_TX_IRQ); 
	}
Compiles without error, maybe it will function also :)

one last question:
setIntPriority(_SPI_1_VECTOR, 4, 0); means: vector priority 4, sub priority 0 - right?

thank you
Matthias

**Comment by majenkotech** [comment]
Yep, you got it :)

It's also good practice to put a `clearIntFlag()` just before the `setIntEnable()` call to ensure the flag is cleared and doesn't trigger immediately you enable the interrupt.

**Comment by madias123** [comment]
yippie! now i'll check this with my oszi. We definitely need a good documentation for this. The real power of the PIC32's are the whole SPI/I2s/... stuff, I'd like to setup nearly everything by hand (Hey, microchip! I need a PIC32 with 8 SPI ports!) :)

**Comment by majenkotech** [comment]
MZ has 6... ;)  Not far off...

**Comment by madias123** [comment]
the MZ has everything...but no floating point, if I remember correctly. That's horrible! Ok, maybe with PIC32MZ EF...

**Comment by majenkotech** [comment]
Yeah, that is one drawback of it.  It would be nice to have hardware FPU.  Still, with the EBI I guess you could interface an external one...

**Comment by majenkotech** [comment]
Maybe dig out an ancient MC68882 ;)  Only 50MHz though...

**Comment by madias123** [comment]
I think of an "one (main)chip virtual synth with analogue filters/VCA's": 
with 6x SPI: 
3x SPI(I2s) = 6 independent Voices (audio DAC's)
3x SPI with octal DAC's   = 24 channel of (8 or 10bit) control voltage for using it with "real" VCA and VCF's
and now with a FPU you'll get the sweetest and craziest sound out of it.
a cheap TFT and some encoders+buttons: ready is the next kickstarter project for an unbelievable price. You must think, the cheapest 4-voice hybrid-digital-analog synth, the Dave smith tetra costs about 700 Euros!

**Comment by majenkotech** [comment]
You could use 6 SPI for 12 voices on DACs, and then use the EBI to interface to as many parallel ADCs as you like.
