### ISSUE TITLE
Feature request: keyboard shortcut to bring up Serial Terminal

### ISSUE THREAD

**Issue by mithat** [UECIDE/UECIDE#63]
The Arduino IDE uses Ctrl+Shift+M as a keyboard shortcut to bring up the serial terminal. I'd be great to have a keyboard shortcut for this in UECIDE as well.

**Comment by majenkotech** [comment]
CTRL-SHIFT-M is already in use for another feature. Another (more suitable) combination will be implemented (CTRL-SHIFT-T? S? Something that links to "serial" or "terminal" in some way...)

**Comment by majenkotech** [comment]
d48d252: Assign CTRL-SHIFT-T to Serial Terminal
