### ISSUE TITLE
handling with MCU specific libaries

### ISSUE THREAD

**Issue by madias123** [UECIDE/UECIDE#65]
Hello,
I was thinking about how can we handle MCU specific libraries with the new plugin "libraries" system. As an example:
The DebouncedInput lib compiles fine on i.e. Chipkit UNO32, but fails on any PIC32MX250xxx.
So how about a compatibilty check for the "installable" libs? but I think this is a hudge of work to do...

**Comment by majenkotech** [comment]
The DebouncedInput should work fine on a 250. I use it with my UltraNano - in fact I updated it specifically to support the 250.  Maybe the wrong version is in the repo, I'll check.

I'm not sure the IDE could deal with CPU-level options like that - it doesn't really have the concept of CPUs - that's down to the core etc to handle that kind of thing.
