### ISSUE TITLE
New board def for pinguino micro

### ISSUE THREAD

**Issue by sker65** [UECIDE/UECIDE#67]
I've done another board definition for the olimex pinguino micro board.

How can I contribute?

br, Steve

**Comment by majenkotech** [comment]
At the moment I am in a transition phase between repository systems.  Best method at the moment is to attach the files zipped up to a post on the forum. I can then take them and turn them into the right packages for distribution.

**Comment by sker65** [comment]
Hi Matt,

I've done a posting in the forum but the forum system says: "you post
need approval" and I can't attach anything?

Could you please check this.

Thanks Steve

Am 19.02.2015 um 22:34 schrieb Matt Jenkins:

**Comment by majenkotech** [comment]
I have authorized your user - you should be able to attach now.

**Comment by sker65** [comment]
Thanks, I've added the board zip file.

br, steve
Am 20.02.2015 um 20:37 schrieb Matt Jenkins:
