### ISSUE TITLE
Teensy plugins missing in beta?

### ISSUE THREAD

**Issue by adamwolf** [UECIDE/UECIDE#70]
Hi!

I was using the latest "stable" release, and the Teensy 3 support worked great.  I tried the beta this morning, and the Teensy 3 plugins didn't appear to be in the Plugin Manager.

I'm on OS X, if that matters.

Thanks!

**Comment by majenkotech** [comment]
I haven't ported the Teensy core over yet to the Beta.  It's on my list.

For Teensy support you may be able to use an existing teensy core / compiler etc from an existing installation with a manual copy of the files.

Porting it is on my list of things to do.

**Comment by adamwolf** [comment]
Oh, no problem.  A new Teensyduino came out today anyway :smile:
