### ISSUE TITLE
Plugin manager window

### ISSUE THREAD

**Issue by driedeker** [UECIDE/UECIDE#72]
the colour of the text in the info window of the plugin manager is light green and dificult to read with my eyes. can it be royal blue

**Comment by majenkotech** [comment]
It should be black.  That said, it uses Java's HTML support which is so piss poor (scuse the language, but there's no other way to describe it) that what colours come out depend on not only the host OS, but the day of the week, the current temperature, and the colour of your socks.  You may find it's orange tomorrow.

**Comment by driedeker** [comment]
Yep it is black now i restated the ide.
cheers.
