### ISSUE TITLE
Red error messages not readable with Darkness theme

### ISSUE THREAD

**Issue by endolith** [UECIDE/UECIDE#75]
**_Default Theme**_ has nice colors and formatting in the compile/error pane:

![2015-04-08 21_02_36-uecide _ fft](https://cloud.githubusercontent.com/assets/58611/7058627/b2102170-de32-11e4-9f81-7e06f91b9b68.png)
![2015-04-08 21_02_47-uecide _ fft](https://cloud.githubusercontent.com/assets/58611/7058626/b20cd862-de32-11e4-8ce9-70a1aa104edb.png)

**_Darkness**_ theme has nice colors in editor pane, but the compiler status is boring and not indented, and red error messages are unreadable on dark gray background:

![2015-04-08 21_03_45-uecide _ untitled6](https://cloud.githubusercontent.com/assets/58611/7058641/d714d06a-de32-11e4-8ecb-a093b48821df.png)
![2015-04-08 21_03_53-uecide _ untitled6](https://cloud.githubusercontent.com/assets/58611/7058642/d717afd8-de32-11e4-8ca5-d57a4fc844bc.png)

**Comment by majenkotech** [comment]
The entire theme system has been rewritten. You can now edit every aspect of it in preferences.
