### ISSUE TITLE
Linux Mint 17.2 cannot install UECIDE!

### ISSUE THREAD

**Issue by gilshultz** [UECIDE/UECIDE#80]
I do not know what I am doing and I cannot get it installed.  I tried everything you posted for linux.

These are the terminal results:

gil@S-Lab ~ $ sudo apt-key adv --keyserver keys.gnupg.net --recv-key CA9F00A1
[sudo] password for gil: 
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.BdZSjnvbm5 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keys.gnupg.net --recv-key CA9F00A1
gpg: requesting key CA9F00A1 from hkp server keys.gnupg.net
gpg: key CA9F00A1: "Majenko Technologies (GPG Key used for signing apt repositories) matt@majenko.co.uk" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gil@S-Lab ~ $ 

It looks like a nice program but I need to install it first.

Thinks

**Comment by majenkotech** [comment]
You have successfully installed the public key for package verification.

    gpg: key CA9F00A1: "Majenko Technologies (GPG Key used for signing apt repositories) matt@majenko.co.uk" not changed
    gpg: Total number processed: 1
    gpg: unchanged: 1

Now, as long as you have added the repository to /etc/apt/sources.list and done an `apt-get update` you should be all set to go `apt-get install uecide` and it should "just work".
