### ISSUE TITLE
0.8.8alpha22 PIC32 Compiler wont install

### ISSUE THREAD

**Issue by jazz1138** [UECIDE/UECIDE#84]
I'd like to report the following issue with the latest version of UECIDE 0.8.8a22.

I have replicated this issue on multiple machines including a clean Windows 10 virtual machine image.

Going to plugins -> boards -> chipkit -> DP32 (and try to install)
It installs everything except the compiler properly
Even trying just the compiler separately… PIC32 for MX MZ fails -
It looks to download properly (reach 100%) then fails to install at around (15-16%)
If you download the compiler from the repo (http://repo.uecide.org/uecide/pool/compilers/p/pic32-tools/pic32-tools_4.8.3-2p9_windows-amd64.deb) and extracted to the compiler folder it works.

**Comment by majenkotech** [comment]
There was a problem with 4.8.3-2p8 in that it had some badly named files in it (they had * in the name) and wouldn't extract in Windows. 4.3.8-2p9 has those files excluded (they are only python files used for debugging).

Make sure that the plugin manager is getting the right version.
