### ISSUE TITLE
Impossible to sign into your forum

### ISSUE THREAD

**Issue by Cliff48** [UECIDE/UECIDE#88]
Impossible to translate the image.  No idea if something is an '0','o','O' ... I gave up.

Enjoying UECide tho, very happy to send Arduino IDE to the trash.

MY reason for wanting to access the forum:
Do you have plans to support other boards.... specifically the ESP8266

Thanks for your time.

**Comment by majenkotech** [comment]
I'm sorry you are experiencing problems with the UECIDE Forums Captcha.

The Captcha we use does not include the letters O or o nor the number 0 specifically because they are hard to distinguish. G and Q, however, do look a little like O and could be confused.
