### ISSUE TITLE
IECIDE Crashed, taken out all board configuration information

### ISSUE THREAD

**Issue by phil6809** [UECIDE/UECIDE#89]
Version 0..8.8alpha22
After a crash while editing a sketch, on restart, the IDE reports no boards installed. Cores, compilers and 
libraries are all intact.
Board.txt files are all in place and not corrupted.
After running plugin manager and rescanning, still no boards.
This is complete ********.
I wont be using this software anymore, I have not got time to reinstall after some trivial malfunction.

**Comment by majenkotech** [comment]
Try deleting your preferences.txt file. And while you're at it, tone down your language.
