### ISSUE TITLE
Suggestion: Ubuntu PPA

### ISSUE THREAD

**Issue by sbrl** [UECIDE/UECIDE#97]
Having a PPA for Ubuntu would make it really easy for Linux users install UECIDE and stay up to date.

**Comment by majenkotech** [comment]
I did start looking at having a PPA but the build system (ant) doesn't seem to work too well with launchpad. (https://launchpad.net/uecide)

Instead you just need to manually add my repository to /etc/apt/sources.list

    deb http://majenko.co.uk/debian stable main
    deb-src http://majenko.co.uk/debian stable main

For testing versions:

    deb http://majenko.co.uk/debian unstable main
    deb-src http://majenko.co.uk/debian unstable main

**Comment by sbrl** [comment]
You have a repository? That'll do just fine! What's the package name? The name `uecide` doesn't show up for me if I run an `apt search uecide`.

**Comment by majenkotech** [comment]
Actually thinking about it only the "unstable" version is there.

**Comment by majenkotech** [comment]
There, the "alpha22" version should be in "stable" now.

**Comment by sbrl** [comment]
Yes! Found it! Thanks so much. It's just so much easier to use a repo / ppa to install stuff. Perhaps the website should show this under the linux instructions?

Also, off topic but how do you package uecide as a .deb and host your own repo? I can't seem to find any decent instructions on the process anywhere.

**Comment by sbrl** [comment]
Erm oh dear. I get an impossible situation if I try to install that package:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 uecide : Depends: openjdk-7-jdk but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by majenkotech** [comment]
It is a bit of a black art. You need to create a "debian" directory and fill it with the right files. You can create a template structure for a project with "dh_make", do it manually, or copy and modify files from an existing project.

Then you can use `dpkg-buildpackage`.  It's quite an involved process getting it right.

Everything in UECIDE is deb based - all the plugins, etc, are .deb files.

**Comment by majenkotech** [comment]
I thought I'd fixed that in that deb. It should be using default-jdk. Hold on...

**Comment by majenkotech** [comment]
Ok, it might work now... You may need to do some purging of caches to pick up the change since the version is the same as before.

**Comment by sbrl** [comment]
Oooh thanks! It does work now :smile:

**Comment by sbrl** [comment]
Oooh thanks! It does work now :smile:
